# Generated by Django 5.0.1 on 2024-01-15 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(blank=True, max_length=50, null=True, verbose_name='Make')),
                ('model', models.CharField(blank=True, max_length=50, null=True, verbose_name='Model')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, null=True, verbose_name='Date')),
                ('total', models.FloatField(blank=True, null=True, verbose_name='Total')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Service name')),
                ('service_price', models.FloatField(blank=True, null=True, verbose_name='Service price')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, max_length=500, null=True, verbose_name='Service')),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='Amount')),
                ('service_price', models.FloatField(blank=True, null=True, verbose_name='Service price')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservice.order')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(blank=True, max_length=50, null=True, verbose_name='Plate number')),
                ('vin', models.CharField(blank=True, max_length=50, null=True, verbose_name='VIN number')),
                ('client', models.CharField(blank=True, max_length=50, null=True, verbose_name='VIN number')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservice.model')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservice.vehicle'),
        ),
    ]
