# Generated by Django 5.0.1 on 2024-01-16 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0002_alter_orderline_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='model',
            options={'verbose_name': 'Model', 'verbose_name_plural': 'Models'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderline',
            options={'verbose_name': 'OrderLine', 'verbose_name_plural': 'OrderLines'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name': 'Vehicle', 'verbose_name_plural': 'Vehicles'},
        ),
    ]
